configurations: []
executionInputs: []
triggers: []
steps:
  - params:
      - name: path
        code: false
        value: ./my-path
    type: clone
    id: clone1
    displayName: Clone Git Repo
    timeout: null
    agent: null
    retries: null
    nextStep: CommandLine1
  - params:
      - name: COMMANDS
        code: false
        value: echo "imported"
      - name: workingDir
        code: false
        value: null
    type: plugin
    id: CommandLine1
    displayName: imported action
    timeout: null
    agent: null
    retries: null
    plugin: CommandLine@1.2.2
    pluginAccount: null
    method: execute
    nextStep: null
  - params: []
    type: clone
    id: clone2
    displayName: Clone Git Repo
    timeout: null
    agent: null
    retries: null
    nextStep: clone1
kaholoVersion: 6.2.0
name: p1-clone-2
description: ''
agent: null
timeout: ''
maxConcurrency: null
firstStep: clone2
