steps:
  - params:
      - name: COMMANDS
        code: false
        value: echo "from git"
      - name: workingDir
        code: false
    type: plugin
    id: CommandLine1
    displayName: CommandLine
    timeout: null
    agent: null
    retries: null
    plugin: CommandLine@1.2.2
    pluginAccount: null
    method: execute
    nextStep: null
triggers: []
configurations: []
executionInputs:
  - required: null
    code: false
    order: 0
    itemType: string
    valueType: string
    id: field1
    viewName: New form field
    description: null
    learnUrl: null
    placeholder: null
    default: null
kaholoVersion: 6.2.0
name: p1
description: ''
agent: null
timeout: null
maxConcurrency: null
firstStep: CommandLine1
id: 65199512f8eb080113abf0eb
content: |
  configurations: []
  executionInputs:
    - required: null
      code: false
      order: 0
      itemType: string
      valueType: string
      id: field1
      viewName: New form field
      description: null
      learnUrl: null
      placeholder: null
      default: null
  triggers: []
  steps:
    - params:
        - name: COMMANDS
          code: false
          value: echo "from git"
        - name: workingDir
          code: false
      type: plugin
      id: CommandLine1
      displayName: CommandLine
      timeout: null
      agent: null
      retries: null
      plugin: CommandLine@1.2.2
      pluginAccount: null
      method: execute
      nextStep: null
  kaholoVersion: 6.2.0
  name: p1
  description: ''
  agent: null
  timeout: null
  maxConcurrency: null
  firstStep: CommandLine1
